export const QUEUE_CONTROLLER_NAME = 'QUEUE_CONTROLLER_NAME';

export const QUEUE_NAME = 'QUEUE_NAME';

export const QUEUE_OPTIONS = 'QUEUE_OPTIONS';

export const MESSAGE_TYPE = 'MESSAGE_TYPE';

export const QUEUE_NAME_SEPARATOR = 'QUEUE_NAME_SEPARATOR';
